# Tell Travis CI to run the test for your Node application
script:
- git checkout prelerna
- lerna publish patch --no-private --yes --registry https://registry.npmjs.org/:_authToken=${NPM_API_TOKEN}

